language: go

matrix:
  include:
  - go: 1.4.3
    env: GOVET=false
  - go: 1.5.4
    env: GOVET=true
  - go: 1.6.4
    env: GOVET=true
  - go: 1.7.6
    env: GOVET=true
  - go: 1.8.5
    env: GOVET=true
  - go: 1.9.2
    env: GOVET=true

install:
  - # Do nothing.

script:
  - go get -t -v ./... github.com/mattn/goveralls
  - go test -v -short -race ./...
  - diff -u <(echo -n) <(gofmt -d -s .)
  - if [ "$GOVET" = "true" ]; then go vet ./...; fi

after_success:
  - for dir in . ./twotier; do go test -short -cover -covermode=count -coverprofile=$dir/profile.out $dir; done
  - (echo mode:\ count; find ./ -name profile.out | xargs grep -vh mode:\ count ) > all.out
  - goveralls -coverprofile=all.out -service=travis-ci
